const fs=require('fs'),path=require('path'),today=new Date().toISOString().slice(0,10),slug=today;
const feed=JSON.parse(fs.readFileSync(path.join(__dirname,'..','feed.json'),'utf8'));
if(feed.posts.find(p=>p.slug===slug)){console.log('Exists');process.exit(0)}
const pool=[[["Excel必会的10个函数：数据处理效率翻倍","VLOOKUP查找数据、SUMIF条件求和、COUNTIF条件计数、IF判断分支、数据透视表秒出报表。","Excel技巧"],["职场沟通的5个黄金法则","先说结论再说过程、主动汇报不要等被问、跨部门先私下对齐再上会、邮件抄送相关人不要群发所有人。","沟通技巧"],["PPT做得好的人都在用的技巧：对齐是灵魂","用参考线和网格线对齐、统一字体和颜色、一页只说一个重点、图片上不要直接放文字加个半透明遮罩。","PPT技巧"]],[["邮件怎么写显得专业：标题正文落款","标题概括主题+项目名+截止日期。正文先说结论再说背景。抄送相关人就行不用全部领导。签名档提前设置好。","职场写作"],["开会时怎么发言让人印象深刻","提前准备3个要点、先说结论再展开、用数据和案例支撑、不超过3分钟。别人发言时做笔记显得认真。","沟通技巧"],["提高工作效率的7个番茄钟使用技巧","25分钟专注+5分钟休息为1个番茄。4个番茄后休15-20分钟。一天完成8-12个番茄就很高效了。","效率提升"]],[["简历怎么写才能过HR的初筛","一页为佳不超过两页。每条经历用动词开头（主导/设计/实现/优化）。匹配JD的关键词。","求职技巧"],["面试必考题：你的优缺点分别是什么","说优点要具体有例子佐证、说缺点要选一个可改进的不是致命短板、说完缺点要补充你在怎么改进。","面试技巧"],["领导力不是当了领导才需要的能力","主动担责、帮助同事、分享知识都是领导力。影响力不是职位给的而是靠专业和靠谱积累的。","管理能力"]],[["工资谈判什么时候谈怎么谈","面试时等对方先提薪资、跳槽加薪20-30%是合理范围、准备好市场数据支撑你的期望薪资。","薪资谈判"],["年终总结怎么写让老板觉得你值钱","不要写流水账。用STAR法则：什么背景+你的行动+产出结果（最好有数据）。重点写你带来的改变。","职场写作"],["如何优雅地拒绝加班","区分紧急和重要的事。紧急+重要马上做、重要不紧急排时间、紧急不重要看能否委托、不重要不紧急直接说不。","效率提升"]],[["情商在职场上到底有多重要","智商决定你能不能做这件事、情商决定你能走多远。控制情绪、换位思考、建立信任关系是核心。","软技能"],["Word排版技巧：目录页眉页脚页码设置","用样式统一标题格式再用自动目录。奇偶页不同页眉、页码从正文开始排（封面目录不用页码）。","办公技巧"],["跳槽的最佳时机和最差时机","金三银四和金九银十是招聘旺季。没拿到offer不要裸辞。工作满1-2年跳一次比较合理。","求职技巧"]],[["PPT配色方案：不会设计也能做出好看的PPT","一个PPT只用2-3种颜色（主色+辅色+强调色）。黑白灰搭配任意一个高饱和色都好看。参考配色网站。","PPT技巧"],["怎么和同事搞好关系但不越界","一起吃饭是最简单的社交方式。工作上多夸赞具体的事情。私事适度分享。不背后议论任何人。","职场关系"],["职场新人最容易犯的5个错误","怕问问题显得无知、开会不敢发言、不懂拒绝什么都接、不及时同步进度、把情绪带到工作中。","职场新人"]],[["Excel数据透视表入门教程","选中数据→插入数据透视表→把字段拖入行列和值区域→自动汇总求和计数平均值。10分钟学会别人以为你是大神。","Excel技巧"],["开会做会议纪要的模板和技巧","会前确认议题、会上记录结论+责任人+deadline、会后24小时内发出。项目名+日期+参与人+决议+待办事项。","职场写作"],["Python自动化办公：10行代码解决重复工作","处理Excel/Word/PDF批量操作、自动发邮件、抓取网页数据。不需要成为程序员学会这3个方向就够了。","效率工具"]],[["怎么管理你的上级：向上管理的艺术","了解老板的关注重点和沟通风格、主动同步进展不要等问、让老板做选择题不是问答题、管理好老板的期望值。","管理能力"],["副业做什么好：不占用太多时间的5个方向","知识付费（写文章做课程）、技能接单（设计开发翻译）、自媒体（小红书公众号）、电商（闲鱼拼多多）、工具站。","副业参考"],["每天被各种消息打断怎么办：专注时间管理","每天固定2-3个查消息的时间不要实时回复。手机通知关掉只留电话和日历提醒。和团队约定紧急事项直接打电话。","效率提升"]]];
const idx=(new Date().getDate()-1)%pool.length,items=pool[idx];
const postTitle=items[0][2]+' | '+today;
feed.posts.unshift({slug,date:today,title:postTitle,items:items.map(i=>({title:i[0],desc:i[1],tag:i[2]}))});
feed.updated=today;
fs.writeFileSync(path.join(__dirname,'..','feed.json'),JSON.stringify(feed,null,2));
const html='<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>'+postTitle+'</title><style>*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}:root{--bg:#fafafa;--card:#fff;--text:#1a1a2e;--t2:#666;--accent:#0891b2;--border:#e5e7eb;--r:10px}body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans SC",sans-serif;background:var(--bg);color:var(--text);line-height:1.7}.container{max-width:800px;margin:0 auto;padding:0 20px}header{background:var(--card);border-bottom:1px solid var(--border);padding:20px 0;margin-bottom:32px}header a{color:var(--accent);text-decoration:none;font-size:.9rem}header h1{font-size:1.3rem;margin-top:8px}.post{background:var(--card);border:1px solid var(--border);border-radius:var(--r);padding:28px}.post .date{color:var(--t2);font-size:.8rem;margin-bottom:20px}.entry{margin-bottom:24px;padding-bottom:20px;border-bottom:1px solid var(--border)}.entry:last-child{border-bottom:none}.entry h3{font-size:1rem;margin-bottom:4px}.entry p{color:var(--t2);font-size:.9rem}.tag{display:inline-block;font-size:.72rem;padding:2px 8px;border-radius:10px;margin-left:6px;background:var(--bg);color:var(--accent)}footer{text-align:center;padding:32px 20px;color:var(--t2);font-size:.8rem}@media(max-width:600px){.post{padding:18px}}</style></head><body><header><div class="container"><a href="../index.html">← 首页</a><h1>'+postTitle+'</h1></div></header><main class="container"><article class="post"><div class="date">📅 '+today+'</div>'+items.map(i=>'<div class="entry"><h3>'+i[0]+' <span class="tag">'+i[2]+'</span></h3><p>'+i[1]+'</p></div>').join('')+'</article></main><footer><p>每日更新</p></footer></body></html>';
fs.writeFileSync(path.join(__dirname,'..','posts',slug+'.html'),html);
console.log('OK');
